---
# Deployment Section

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project2-test-app
  template:
    metadata:
      labels:
        app: project2-test-app
    spec:
      containers:
      - name: project2-test-container
        image: cliffordanup/intellipaat-project1:${BUILD_NUMBER}.$(git log -1 --format=%h)
        ports:
        - containerPort: 80
      tolerations:
      - key: "TestNode"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

---
# Service Section

apiVersion: v1
kind: Service
metadata:
  name: project2-test-service
spec:
  selector:
    app: project2-test-app
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 80
    nodePort: 30000
    protocol: TCP
